
INFO 2024-07-05 21:37:03,345 autoreload 12072 2272 Watching for file changes with StatReloader
INFO 2024-07-05 21:37:06,208 views 12072 9252 Index page accessed
INFO 2024-07-05 21:37:06,209 basehttp 12072 9252 "GET / HTTP/1.1" 200 121
WARNING 2024-07-05 21:37:06,346 log 12072 9252 Not Found: /favicon.ico
WARNING 2024-07-05 21:37:06,347 basehttp 12072 9252 "GET /favicon.ico HTTP/1.1" 404 2545
INFO 2024-07-05 21:37:50,420 basehttp 12072 9252 "GET /hw2/ HTTP/1.1" 200 1273
INFO 2024-07-05 21:37:54,201 basehttp 12072 9252 "GET /hw2/orders/ HTTP/1.1" 200 2065
INFO 2024-07-05 21:38:18,952 views 12072 9252 Index page accessed
INFO 2024-07-05 21:38:18,952 basehttp 12072 9252 "GET / HTTP/1.1" 200 121
INFO 2024-07-05 21:38:26,941 basehttp 12072 9252 "GET /hw2/ HTTP/1.1" 200 1273
INFO 2024-07-05 21:38:30,314 basehttp 12072 9252 "GET /hw2/orders/ HTTP/1.1" 200 2065
INFO 2024-07-05 21:41:04,591 basehttp 12072 9252 "GET /hw2/orders/ HTTP/1.1" 200 2221
INFO 2024-07-05 23:07:30,167 autoreload 1348 520 Watching for file changes with StatReloader
INFO 2024-07-05 23:07:31,947 views 1348 10392 Index page accessed
INFO 2024-07-05 23:07:31,948 basehttp 1348 10392 "GET / HTTP/1.1" 200 121
INFO 2024-07-05 23:07:41,486 basehttp 1348 10392 "GET /hw2/ HTTP/1.1" 200 1134
ERROR 2024-07-05 23:07:46,051 log 1348 10392 Internal Server Error: /hw2/orders/
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 44, in orders
    return render(request, "hw3/orders.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3/orders.html
ERROR 2024-07-05 23:07:46,054 basehttp 1348 10392 "GET /hw2/orders/ HTTP/1.1" 500 81395
INFO 2024-07-05 23:08:23,927 autoreload 1348 520 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:08:24,334 autoreload 17296 2924 Watching for file changes with StatReloader
ERROR 2024-07-05 23:08:29,590 log 17296 13288 Internal Server Error: /hw2/orders/
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 44, in orders
    return render(request, "hw3app/orders.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3app/orders.html
ERROR 2024-07-05 23:08:29,603 basehttp 17296 13288 "GET /hw2/orders/ HTTP/1.1" 500 81586
ERROR 2024-07-05 23:08:30,814 log 17296 13288 Internal Server Error: /hw2/orders/
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 44, in orders
    return render(request, "hw3app/orders.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3app/orders.html
ERROR 2024-07-05 23:08:30,816 basehttp 17296 13288 "GET /hw2/orders/ HTTP/1.1" 500 81586
ERROR 2024-07-05 23:08:31,953 log 17296 13288 Internal Server Error: /hw2/orders/
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 44, in orders
    return render(request, "hw3app/orders.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3app/orders.html
ERROR 2024-07-05 23:08:31,956 basehttp 17296 13288 "GET /hw2/orders/ HTTP/1.1" 500 81586
INFO 2024-07-05 23:08:39,009 autoreload 17296 2924 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:08:39,419 autoreload 17212 8628 Watching for file changes with StatReloader
ERROR 2024-07-05 23:08:43,141 log 17212 16120 Internal Server Error: /hw2/orders/
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 44, in orders
    return render(request, "hw2app/orders.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw2app/orders.html
ERROR 2024-07-05 23:08:43,143 basehttp 17212 16120 "GET /hw2/orders/ HTTP/1.1" 500 81586
INFO 2024-07-05 23:09:02,241 autoreload 17212 8628 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:09:02,651 autoreload 16852 16176 Watching for file changes with StatReloader
INFO 2024-07-05 23:09:05,871 basehttp 16852 16812 "GET /hw2/orders/ HTTP/1.1" 200 2239
ERROR 2024-07-05 23:09:13,104 log 16852 16812 Internal Server Error: /hw2/orders/2
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 19, in orders
    client = get_object_or_404(Client, id=client_id)
                               ^^^^^^
NameError: name 'Client' is not defined
ERROR 2024-07-05 23:09:13,107 basehttp 16852 16812 "GET /hw2/orders/2 HTTP/1.1" 500 64897
ERROR 2024-07-05 23:09:37,912 log 16852 16812 Internal Server Error: /hw2/orders/1
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 19, in orders
    client = get_object_or_404(Client, id=client_id)
                               ^^^^^^
NameError: name 'Client' is not defined
ERROR 2024-07-05 23:09:37,914 basehttp 16852 16812 "GET /hw2/orders/1 HTTP/1.1" 500 64897
ERROR 2024-07-05 23:09:40,142 log 16852 16812 Internal Server Error: /hw2/orders/1
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 19, in orders
    client = get_object_or_404(Client, id=client_id)
                               ^^^^^^
NameError: name 'Client' is not defined
ERROR 2024-07-05 23:09:40,144 basehttp 16852 16812 "GET /hw2/orders/1 HTTP/1.1" 500 65034
INFO 2024-07-05 23:10:51,169 autoreload 16852 16176 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:10:51,572 autoreload 608 8736 Watching for file changes with StatReloader
ERROR 2024-07-05 23:11:00,069 log 608 4924 Internal Server Error: /hw2/orders/1
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 20, in orders
    order = Order.objects.filter(buyer=client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'buyer' into field. Choices are: client, client_id, id, order, order_date, total_amount
ERROR 2024-07-05 23:11:00,086 basehttp 608 4924 "GET /hw2/orders/1 HTTP/1.1" 500 111751
INFO 2024-07-05 23:11:31,707 autoreload 608 8736 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:11:32,109 autoreload 5784 14068 Watching for file changes with StatReloader
ERROR 2024-07-05 23:11:36,941 log 5784 12128 Internal Server Error: /hw2/orders/1
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 21, in orders
    today = timezone.now()
            ^^^^^^^^^^^^
AttributeError: type object 'datetime.timezone' has no attribute 'now'
ERROR 2024-07-05 23:11:36,943 basehttp 5784 12128 "GET /hw2/orders/1 HTTP/1.1" 500 65629
INFO 2024-07-05 23:12:20,400 autoreload 5784 14068 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:12:20,819 autoreload 16432 4992 Watching for file changes with StatReloader
INFO 2024-07-05 23:12:22,128 autoreload 16432 4992 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:12:22,526 autoreload 16940 4144 Watching for file changes with StatReloader
INFO 2024-07-05 23:12:23,836 autoreload 16940 4144 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:12:24,211 autoreload 16176 4436 Watching for file changes with StatReloader
INFO 2024-07-05 23:12:27,564 autoreload 16176 4436 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:12:27,967 autoreload 3288 11440 Watching for file changes with StatReloader
INFO 2024-07-05 23:12:33,349 autoreload 3288 11440 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:12:33,743 autoreload 5916 14068 Watching for file changes with StatReloader
INFO 2024-07-05 23:12:39,122 autoreload 5916 14068 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:12:39,534 autoreload 12068 3292 Watching for file changes with StatReloader
ERROR 2024-07-05 23:12:42,245 log 12068 9192 Internal Server Error: /hw2/orders/1
Traceback (most recent call last):
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Алексей\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Домашка\Django\hwproject\hw2app\views.py", line 29, in orders
    products_week = {product for order in order_week for product in order.products.all()}
                                                                    ^^^^^^^^^^^^^^
AttributeError: 'Order' object has no attribute 'products'
ERROR 2024-07-05 23:12:42,247 basehttp 12068 9192 "GET /hw2/orders/1 HTTP/1.1" 500 66908
INFO 2024-07-05 23:13:07,440 autoreload 12068 3292 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:13:07,854 autoreload 3536 14600 Watching for file changes with StatReloader
INFO 2024-07-05 23:13:10,209 autoreload 3536 14600 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:13:10,580 autoreload 3000 13288 Watching for file changes with StatReloader
INFO 2024-07-05 23:13:11,881 autoreload 3000 13288 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:13:12,256 autoreload 8664 17212 Watching for file changes with StatReloader
INFO 2024-07-05 23:13:14,575 autoreload 8664 17212 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:13:14,958 autoreload 3292 12068 Watching for file changes with StatReloader
INFO 2024-07-05 23:13:28,499 autoreload 3292 12068 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:13:28,901 autoreload 5476 11708 Watching for file changes with StatReloader
INFO 2024-07-05 23:13:34,285 autoreload 5476 11708 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:13:34,679 autoreload 5332 16584 Watching for file changes with StatReloader
INFO 2024-07-05 23:13:40,079 autoreload 5332 16584 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:13:40,456 autoreload 4928 8388 Watching for file changes with StatReloader
INFO 2024-07-05 23:13:43,504 basehttp 4928 16116 "GET /hw2/orders/1 HTTP/1.1" 200 1927
INFO 2024-07-05 23:14:02,580 basehttp 4928 16116 "GET /hw2/orders/3 HTTP/1.1" 200 1926
INFO 2024-07-05 23:15:34,932 autoreload 4928 8388 E:\Домашка\Django\hwproject\hw2app\views.py changed, reloading.
INFO 2024-07-05 23:15:35,336 autoreload 17280 2600 Watching for file changes with StatReloader
